apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: cpo3sm74w-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: cpo3sm74w-nodejs 
  name: cpo3sm74w-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: cpo3sm74w-nodejs 
